teleop_twist_joy_node:
  ros__parameters:
    frame: "base_link"
    publish_stamped_twist: true
    require_enable_button: false
    enable_turbo_button: 0
    
    # Removed Y-axis (No strafing on diff drive)
    axis_linear:
      x: 1
    axis_angular:
      yaw: 2

    scale_linear:
      x: 0.6
    scale_linear_turbo:
      x: 0.6

    scale_angular:
      yaw: 8.0
    scale_angular_turbo:
      yaw: 4.0

    inverted_reverse: true

teleop_twist_keyboard_node:
  ros__parameters:
    frame_id: "base_link"
    stamped: true
    speed: 0.6  # Default starting linear velocity (m/s)
    turn: 8.0

imu_feedback_node:
  ros__parameters:
    alpha: 1.0
    mid_point: 5.0

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 100.0
    robot_feedback: "OPEN_LOOP"
    max_velocity: [0.6, 0.0, 8.0]
    min_velocity: [-0.6, 0.0, -8.0]
    max_accel: [100.0, 0.0, 100.0]
    max_decel: [-100.0, 0.0, -100.0]
    enable_stamped_cmd_vel: true